.TH "THAIDATE" 1 "2018-05-19" "Linux Programmer's Manual"


.SH NAME

.P
\fBthaidate\fR \- accepts 3 numbers, year, month and day, and outputs
a date string in Thai language with the month using the Thai name.

.SH SYNOPSIS

.P
\fBthaidate\fR [option] \fBy m d\fR.

.SH DESCRIPTION

.P
\fBthaidate\fR accepts as input, 3 numbers which by default must be in
order of 4 digit year, month number [1..12], and day [1..\fImaxday\fR],
where \fImaxday\fR is calculated by month and year. You may alter the
default order of input fields using options.

.P
By default the \fBoutput\fR order is \fBd m y\fR and also by default Latin
digits are used for the numbers, \fBd\fR and \fBy\fR.

.P
The Thai calendar year is 543 years ahead of the normally accepted
Western calendar. This increment is added to the output year.

.SH OPTIONS

.TP
 \fB\-h\fR, \fB\-\-help\fR
print help information and exit.

.TP
 \fB\-m\fR, \fB\-\-mdy\fR
order the input date fields as month, day and year.

.TP
 \fB\-d\fR, \fB\-\-dmy\fR
order the input date fields as day, month and year.

.TP
 \fB\-y\fR, \fB\-\-ymd\fR
order the input date fields as year, month and day. This is actually the
default.

.TP
 \fB\-Y\fR, \fB\-\-YMD\fR
orders the \fBoutput\fR field as year, month, day. This the officially
recognised Thai date format. But in spite of this, the \fIdefault\fR
output ordering is more usual.

.TP
 \fB\-D\fR, \fB\-\-DMY\fR
orders the \fBoutput\fR field as day, month, year. This the most common
Thai date format, and it is the default.

.TP
 \fB\-r\fR, \fB\-\-real\-thai\fR
Latin digits are used very commonly in Thailand in many situations,
no doubt thanks to the use the ubiquitous electronic calculator. So,
by default the output of this program uses Latin digits for the day and
year fields. Choosing this option will output Thai digits for numbers
instead.

Example: \fBthaidate\fR \-\-real\-thai 2018 1 31

\fB๓๑ มกราคม ๒๕๖๑\fR

.SH BUGS/FEATURES

.P
Though within Thai writing spaces are not as commonly used as in
English, the writing is by no means space free. Because I \fIseem\fR to
recall having seen spaces in Thai dates, I have chosen to follow my
belief. I shall certainly change this on viewing evidence to the
contrary.

.SH AUTHOR

.P
Robert L Parker rlp1938@gmail.com

.SH SEE ALSO

.P
\fBdate\fR (1)

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man thaidate.t2t
